language: php

php:
  - 7
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - php vendor/bin/php-coveralls -v -x coverage.clover -o coveralls-upload.json
